# Generated by Django 2.1.1 on 2018-09-01 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20180901_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='move',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='lastTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='time1',
            field=models.IntegerField(default=900000),
        ),
        migrations.AlterField(
            model_name='match',
            name='time2',
            field=models.IntegerField(default=900000),
        ),
        migrations.AddField(
            model_name='usere',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Match'),
        ),
        migrations.AddField(
            model_name='usere',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
