# Generated by Django 2.1.1 on 2018-09-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180901_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='lastTime',
            field=models.BigIntegerField(),
        ),
    ]
